# Generated by Django 4.2 on 2025-10-13 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_room_room_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_type',
        ),
        migrations.AddField(
            model_name='room',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='home.hotel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(default='available', max_length=20),
        ),
        migrations.DeleteModel(
            name='RoomType',
        ),
    ]
