# Generated by Django 5.2.7 on 2025-11-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_room_room_type_room_hotel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
